### ISSUE TITLE
The bot goes into infinite loop when a meeting in Cancelled

### ISSUE THREAD

**Issue by WINOFFRG** [TobiasPankner/Teams-Auto-Joiner#115]
**Describe the bug**
When a meeting gets canceled it is still listed in the Calendar. But the meeting link is not present, So in the meeting found list the bot keeps on trying for the canceled meeting and goes into Infinite Loop.

**To Reproduce**
1. Schedule a meeting and start the Bot.
2. Cancel a meeting before the bot joins it.
3. You will see an infinite loop where it is unable to identify the condition when the meeting is canceled, Skip it.

**Screenshots**
![image](https://user-images.githubusercontent.com/61311751/120429735-8beb6200-c393-11eb-91fe-d8d8a6807e28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu
 - Browser: Chrome
 - Version: Ver. 91

**Comment by TobiasPankner** [comment]
This is obviously not how this is intended to work but it shouldn't actually have an effect on the function of the bot. If there is a new meeting it will still join it normally.  
If this is not the case, or you just want to ignore the canceled meeeting because it's annoying, you can do the following.  
Put this regex `.*Canceled:.*` into the `blacklist_meeting_re` option of the config. This will completely ignore all meetings with the text "Canceled:" anywhere in the title.

**Comment by TobiasPankner** [comment]
And just because I'm curious, what version of the bot are you using? For future issues, always update to the newest version first.

**Comment by WINOFFRG** [comment]
Thanks for the Regex TIP! I am using the latest version which has the latest commits.

**Comment by TobiasPankner** [comment]
Are you sure about the version? Because the `Waiting for the calendar to load...` in your screenshot is not in the original code.

**Comment by WINOFFRG** [comment]
I made a few changes to the code in the python file. As it was consuming a lot of memory on my Azure Server.
BTW This isn't a big deal for me as our meetings usually don't get canceled and if so the Regex would work. 

**The more serious issue other than this one is when the bot leaves a particular meeting after minimum members condition. It lists the meeting on the calendar but never joins it. Here I tested both the codes mines modified version and yours original without anything change. I have been nothing this issue for a long time and every day after one meeting ends, I have to restart the script.**

As far as I have observed, in 90% of the cases, it doesn't join, It just keeps on listing the meeting.
I am running this script on Ubuntu Server via SSH.

In case you feel this is a serious issue, I will be happy to raise a proper PR with complete logs, images, details, and even Video.

**Comment by TobiasPankner** [comment]
Some of the calendar meeting code is pretty messy.  
This is because I cannot test calendar meetings as I only have the free version of Teams which (as far as I know) doesn't support them.  
If you make any changes to the calendar code, I'd be happy to merge them as long as they are properly tested and documented.  
Just know that it is very difficult for myself to fix issues regarding this part of the program.

**Comment by WINOFFRG** [comment]
Want to let you know that the issue is the same in `Only Channel Mode`.
If you have a solution to this problem, Great enough as it seems a major issue to me.

Other than this, I will try checking the code again to make it more optimized and get this script running in a more efficient way.

**Comment by TobiasPankner** [comment]
Okay, please create a new issue with the minimum member problem. I will take a look at it.
