### ISSUE TITLE
Not joining meeting after leaving

### ISSUE THREAD

**Issue by Peppedoc** [TobiasPankner/Teams-Auto-Joiner#41]
Hi, when there are 2 or more meetings simultaneously, your program joins only one. Then after 5 tentatives leaves the meeting if there are less then 2(?) (I changed the value to 10 so I don't remember the exact value... oops)  but cannot connect to the other one and enters in an infinite loop looking for new meetings. 

Could you try solve this problem? Thanks a lot

**Comment by TobiasPankner** [comment]
So am I understanding this correctly, you have 2 meetings that started at the same time and when it leaves one of these it doesn't join the other one?

**Comment by TobiasPankner** [comment]
Well, once the bot leaves one meeting it only joins newer ones again.

**Comment by Peppedoc** [comment]
Yes, but it doesn't join any new meeting.

**Comment by TobiasPankner** [comment]
And what is the start time of these meetings it should join? A console log or video would be really helpful

**Comment by Peppedoc** [comment]
Think I understood what you mean.
But, if I can, wouldn't be better putting only already joined meetings in a blacklist so that even though an other meeting started before the end of this the program can still enter?

**Comment by TobiasPankner** [comment]
I understand why this would be useful to you.  
But you also have to understand that this would cause alot of chaos becauce old meetings are often left there. Just imagine that the program leaves the newest meeting and then joins a meeting from 5 hours ago which is still open. This is why I decided to only ever attend the newest meeting.  
If you have a suggestion to fix this problem, I'll be open to it. But for now I will close this issue because this is the inteded behaviour.
